title: Introduction to Experimentation in Physics (TN2985)
author: Freek Pols
logo: figures/TUDelft_logo_rgb.png #add your own logo here

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://github.com/Contemporary-Physicslab/TN2985/" #Replace this with your own URL

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/TeachBooks/template" #add your own repo URL here
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
  extra_extensions:
    - sphinx.ext.imgconverter
    #- sphinx_exercise
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx-tudelft-theme

bibtex_bibfiles: 
  - references.bib
